name: test
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: setup forge
        run: forge install

      - name: setup node
        run: yarn install

      - name: setup pyenv
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install dependencies
        run: python -m pip install -r requirements.txt

      - name: set solidity compiler version
        run: |
          solc-select install 0.8.16
          solc-select use 0.8.16

      - name: prettier & solhint
        run: yarn scan

      - name: static analysis
        run: yarn slither

      - name: Run tests
        run: forge test  --gas-report
