name: CI
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup node
        run: yarn install --immutable
      - name: prettier & solhint
        run: yarn scan

  static-analysis:
    name: Static analysis (slither)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run slither
        uses: crytic/slither-action@v0.2.0
        continue-on-error: true
        with:
          fail-on: "config"
          target: "src"

  test:
    name: Test (forge)
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Setup forge
        run: forge install
      - name: Run tests
        run: forge test  --gas-report
